apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-cluster
  template:
    metadata:
      labels:
        app: flink-cluster
    spec:
      containers:
        - name: jobmanager
          imagePullPolicy: Always
          image: flink:latest
          envFrom:
            - configMapRef:
                name: flink-configmap-jobmanager
          ports:
            - containerPort: 8081 # JobManager web UI port

        - name : taskmanager
          imagePullPolicy : Always
          image : flink:latest
          envFrom :
            - configMapRef :
                name : flink-configmap-taskmanager

---
apiVersion : v1
kind       : ConfigMap
metadata   :
  name     : flink-configmap-jobmanager
data       :
   conf.yaml         : |-
    jobmanager.rpc.address
    log4j.properties

---
apiVersion : v1
kind       : ConfigMap
metadata   :
  name     : flink-configmap-taskmanager
data       :
   conf.yaml             				# TaskManager configuration file